version: '3.4'

services:
  docker-optimization:
    build:
      context: .
      dockerfile: ./dockerfiles/v5/Dockerfile
      target: develop
    command: npm run dev
    volumes:
      - /code/node_modules
    ports:
      - 8080:8080
